#!/bin/sh

#
# Enlightenment Builder (c) @burzumishi 2014
#

#
# GitHub: https://github.com/burzumishi/E-Builder
# GitHub Page: http://burzumishi.github.io/E-Builder
#

#
# Set your install PREFIX and DISTRO
#

PREFIX="/usr";
#DISTRO="debian.sid";
DISTRO="ubuntu.1404";


#
# Set your Optimization FLAGS
#

CFLAGS="";
CXXFLAGS="";

#
# E-Builder Main Routine (DO NOT TOUCH these settings) 
#

RELEASE="$1";

if [ ! -z "$RELEASE" ]; then
	echo
	echo "./E-Builder [Tar|Git]";
	echo
fi;

ERULES="$PWD/E-Rules/$DISTRO";
ELOG="$PWD/log";
ESOURCES="$PWD/src";

EGITURL="https://git.enlightenment.org";

REPOSITORIES=$(grep -v ^# E-${RELEASE}.release);

DEPENDENCIES=$(grep -v ^# E-Dependencies/${DISTRO} | awk -v ORS=" " '{print $0}');

#
# Start Enlightenment Build!
#

echo
echo " >>> Enlightenment Desktop Environment (E-Builder) <<<";
echo
echo "    >>> E-Builder is working under ($DISTRO) <<<";
echo
echo "                  >>> $RELEASE <<<";
echo

#
# Install Dependencies
#

echo
echo " * E-Builder: Installing necessary dependencies ...";
echo

SUDO=$(which sudo);

$SUDO apt-get install $DEPENDENCIES;

#
# Download and Install Packages from Git Repos
#

if [ ! -d "$ESOURCES" ]; then mkdir -p $ESOURCES; fi;
if [ ! -d "$ELOG" ]; then mkdir -p $ELOG; fi;

case $RELEASE in

	git|GIT|Git)

# Git Release Builder
for gitrepo in $REPOSITORIES; do

	cd $ESOURCES;
	
	#
	# Obtain package name
	#

	package=$(echo $gitrepo | awk -F/ '{print $NF}' | sed 's/\.git//g');

	#
	# Download Source from GIT
	#

	echo
	echo " * E-Builder: Downloading <$package> from git repository ...";
	echo

	git clone $EGITURL/$gitrepo;

	#
	# Build Package
	#

	echo
	echo " * E-Builder: Building <$package> from git sources ...";
	echo

	cd $ESOURCES/$package;

	cp $ERULES/$package $ESOURCES/$package/${package}.rules;

	chmod +x $ESOURCES/$package/${package}.rules;

	if [ ! -f "configure" ]; then sh autogen.sh; fi;

	if [ -f "Makefile" ]; then make distclean; make clean; fi;

	sh ${package}.rules $PREFIX | tee -a $ELOG/${package}.log;

	cd ..;

	echo
	echo " * E-Builder: Package <$package> installed.";
	echo
	
done;
	;;
	
	tar|TAR|Tar|stable|STABLE|Stable)

# Git Release Builder
for tarball in $REPOSITORIES; do

	cd $ESOURCES;
	
	#
	# Obtain package name
	#

	package=$(echo $tarball | awk -F/ '{print $NF}' | sed 's/\.tar\.gz//g');

	#
	# Download Source from Enlightenment Web Site
	#

	echo
	echo " * E-Builder: Downloading <$package> from Enlightenment website ...";
	echo

	git clone $EGITURL/$gitrepo;

	#
	# Build Package
	#

	echo
	echo " * E-Builder: Building <$package> from tarball sources ...";
	echo

	cd $ESOURCES/$package;

	cp $ERULES/$package $ESOURCES/$package/${package}.rules;

	chmod +x $ESOURCES/$package/${package}.rules;

	# if [ ! -f "configure" ]; then sh autogen.sh; fi;

	if [ -f "Makefile" ]; then make distclean; make clean; fi;

	sh ${package}.rules $PREFIX | tee -a $ELOG/${package}.log;

	cd ..;

	echo
	echo " * E-Builder: Package <$package> installed.";
	echo
	
done;

	;;

	*) echo
	   echo " * E-Builder: Use <Tar> or <Git>.";
	   echo
	   exit 1;
	;;
esac

exit 0;
